version: "3.11"
services:
  db:
    image: postgres:latest
    container_name: academyloadcalculator_db
    environment:
        POSTGRES_PASSWORD: "1234"
        POSTGRES_DB: "academyloadcalculator"
        POSTGRES_USER: "postgres"
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: academyloadcalculator_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - static_volume:/home/app/src/staticfiles/
    env_file:
      - env-production
    command: ["/home/app/scripts/startApp.sh"]
    restart: always

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/src/staticfiles/
    ports:
      - 1337:80
    depends_on:
      - app
volumes:
  postgres_data:
  static_volume:
