# Generated by Django 4.2.5 on 2023-10-25 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Degree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("number_of_students", models.PositiveIntegerField()),
                ("cipher", models.CharField(max_length=50)),
                ("direction", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_name", models.CharField(max_length=100)),
                ("load", models.PositiveIntegerField()),
                ("salary", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "holding_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Практическое занятие", "Практическое занятие"),
                            ("Лабораторная работа", "Лабораторная работа"),
                            ("Лекция", "Лекция"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("course", models.PositiveIntegerField()),
                ("semester", models.PositiveIntegerField()),
                ("group_name", models.CharField(max_length=255)),
                ("total_time_for_group", models.PositiveIntegerField()),
                ("used", models.BooleanField()),
                ("semester_duration", models.PositiveIntegerField()),
                (
                    "study_level",
                    models.CharField(
                        choices=[
                            ("Бакалавриат", "Бакалавриат"),
                            ("Магистратура", "Магистратура"),
                            ("Специалитет", "Специалитет"),
                            ("Аспирантура", "Аспирантура"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subject_type", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=255)),
                ("credit", models.PositiveIntegerField()),
                ("cipher", models.CharField(max_length=255)),
                ("direction", models.CharField(max_length=255)),
                (
                    "groups",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("phone_number", models.CharField(max_length=30)),
                ("rate", models.FloatField()),
                (
                    "academic_title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.academictitle",
                    ),
                ),
                (
                    "degree",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.degree",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.position",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        to="website.subject", verbose_name="subjects"
                    ),
                ),
            ],
        ),
    ]
