# Generated by Django 4.2.5 on 2023-10-02 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('students_amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=100)),
                ('load', models.PositiveIntegerField()),
                ('salary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('holding_type', models.CharField(choices=[('Семинар', 'Семинар'), ('Лабораторная работа', 'Лабораторная работа'), ('Лекция', 'Лекция')], max_length=50)),
                ('course', models.PositiveIntegerField()),
                ('semester', models.PositiveIntegerField()),
                ('group_name', models.CharField(max_length=50)),
                ('total_time_for_group', models.PositiveIntegerField()),
                ('used', models.BooleanField()),
                ('semester_duration', models.PositiveIntegerField()),
                ('study_level', models.CharField(choices=[('Бакалавриат', 'Бакалавриат'), ('Магистратура', 'Магистратура'), ('Специалитет', 'Специалитет'), ('Аспирантура', 'Аспирантура')], max_length=50)),
                ('subject_type', models.CharField(choices=[('Курсовые работы / проекты', 'Курсовые работы / проекты'), ('Базовая компонента', 'Базовая компонента'), ('Вариативная компонента', 'Вариативная компонента'), ('Часть, формируемая участниками образовательных отношений', 'Часть, формируемая участниками образовательных отношений'), ('Практики и НИР', 'Практики и НИР'), ('Государственная итоговая аттестация', 'Государственная итоговая аттестация'), ('Факультатив', 'Факультатив'), ('Дисциплины по выбору', 'Дисциплины по выбору')], max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('credit', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=30)),
                ('degree', models.CharField(max_length=50)),
                ('academic_title', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.FloatField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.position')),
                ('subjects', models.ManyToManyField(to='website.subject', verbose_name='subjects')),
            ],
        ),
    ]
