# Generated by Django 4.2.5 on 2023-10-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="holding_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Практическое занятие", "Практическое занятие"),
                    ("Лабораторная работа", "Лабораторная работа"),
                    ("Лекция", "Лекция"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
