# Generated by Django 4.2.5 on 2023-10-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_rename_name_group_cipher_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="name",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
