# Generated by Django 4.2.5 on 2023-10-02 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_subject_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="groups",
        ),
        migrations.AddField(
            model_name="subject",
            name="groups",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.group",
            ),
            preserve_default=False,
        ),
    ]
