# Generated by Django 4.2.5 on 2023-10-02 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_remove_subject_groups_subject_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="groups",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.group",
            ),
        ),
    ]
